resolver: lts-17.11

packages:
  - .

extra-deps:
  - http2-client-0.10.0.0
  - proto3-suite-0.4.2
  - proto3-wire-1.2.2
  - git: git@github.com:ProofOfKeags/http2-grpc-haskell.git
    commit: 0bedd4acfda825a154f4af8bf1d3ce89067ee986
    subdirs:
      - http2-client-grpc
      - http2-grpc-proto-lens
      - http2-grpc-proto3-wire
      - http2-grpc-types
      - warp-grpc
